class: !function ../parallelbench_task.ParallelBenchTask
dataset_path: furiosa-ai/ParallelBench
num_fewshot: 0
output_type: generate_until
generation_kwargs:
  until:
    - "\n\n"
  do_sample: false
  max_tokens: 64
test_split: test
