group: parallel_bench_text_writing
group_alias: "ParallelBench - Text Writing"
aggregate_metric_list:
  - metric: score
    aggregation: mean
    weight_by_size: true
  - metric: nfe
    aggregation: mean
    weight_by_size: true
  - metric: tokens_per_step
    aggregation: mean
    weight_by_size: true
task:
  - parallel_bench_text_writing_paraphrasing
  - parallel_bench_text_writing_summarization
  - parallel_bench_text_writing_words_to_sentence_easy
  - parallel_bench_text_writing_words_to_sentence_medium
  - parallel_bench_text_writing_words_to_sentence_hard
