group: parallel_bench_waiting_line
group_alias: "ParallelBench - Waiting Line"
aggregate_metric_list:
  - metric: score
    aggregation: mean
    weight_by_size: true
  - metric: nfe
    aggregation: mean
    weight_by_size: true
  - metric: tokens_per_step
    aggregation: mean
    weight_by_size: true
task:
  - parallel_bench_waiting_line_copy
  - parallel_bench_waiting_line_reverse
  - parallel_bench_waiting_line_sort
  - parallel_bench_waiting_line_shuffle
  - parallel_bench_waiting_line_insert_index
  - parallel_bench_waiting_line_insert_random
  - parallel_bench_waiting_line_remove_index
  - parallel_bench_waiting_line_remove_random
  - parallel_bench_waiting_line_replace_index
  - parallel_bench_waiting_line_replace_random
