include: _base.yml
task: parallelbench_puzzles_latin_square_n4_rules_3shot_cyclic
metadata:
  parallelbench_task: "puzzles/latin_square_n4_rules_3shot_cyclic"
  flex_config:
    size: 4
    num_samples: 100
